# config.yaml
# 数据集配置
datasets:
  - name: "mmlu_dev"
    local_path: "data\\mmlu_dev.jsonl"
  

# 模型配置
models:
  - name: "Qwen"
    model_name: "Qwen/Qwen2-7B-Instruct"
    local_path: "models\\Qwen2-7B-Instruct"  # 改为相对路径
    trust_remote_code: true
  
  - name: "DeepSeek"
    model_name: "deepseek-ai/deepseek-coder-6.7b-instruct"
    local_path: "models\\deepseek-coder-6.7b-instruct"  # 改为相对路径
  
  - name: "智谱 (ChatGLM)"
    model_name: "zai-org/chatglm3-6b"
    local_path: "models\\chatglm-6b" 
    trust_remote_code: true
  
  - name: "全部模型"
    is_all_option: true

  # name: Qwen-7B
  # tokenizer: /path/
  # full:
  #   throughput: 300
  #   world_size: 8
  # lora:
  #   throughput: 500
  #   world_size: 1